### ISSUE TITLE
Mostrando Issue p Raiane

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#107]
Aqui conseguimos incluir até **markdown**

> Aqui eu inclui tudo que a Natália colocou no formulário

# Minhas perguntas

- Pergunta 1
- Pergunta 2
- Por ai vai

Isso tem referência no [issue](https://github.com/automatiza-mg/automatizacoes/issues/121).

- [x] Tenho que arrumar minha cama.
- [x] Tenho que lavar roupa.
- [ ] Tenho que colocar o frango no forno.
- [ ] Tenho que fazer meu café após o almoço na moka.

**Comment by raianecardoso** [comment]
Oi, eu consegui entender como funciona. O Gabriel é um grão mestre do GitHub.

**Comment by gabrielbdornas** [comment]
Depois deste comentário pertinente (FANCE) vamos fechar nosso Issue!!!!

**Comment by gabrielbdornas** [comment]
- [ ] Tenho que arrumar minha cama.
- [ ] Tenho que lavar roupa.
- [ ] Tenho que colocar o frango no forno.
- [ ] Tenho que fazer meu café após o almoço na moka.
