### ISSUE TITLE
Governança reunião de tira dúvidas

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#109]
[Resultado desta discussão](https://github.com/automatiza-mg/handbook/issues/109#issuecomment-2130074661).

See #108 

@automatiza-mg/dcd proponho aqui algumas ideias para organizarmos nossas reuniões de tira-dúvidas. A questão é criar uma padronização que permitirá aos não participantes do dia, tendo em vista que é uma agenda não obrigatória, acompanhar o trabalho de maneira assíncrona.

## Sugestões:
- Gravar a transcrição do encontro para gerar ata via IA.
  - Transcrição salvo em repositório privado.
  - Publicação apenas da parte revisada do encontro.
- Eleição no início da reunião de quem ficará responsável pela documentação.
  - Produto final do encontro será um post no repositório handbook.
- Sorteio da priorização das dúvidas que serão analisadas (caso haja muitas).
- Utilização de label `tira-duvidas` para filtrar dúvidas que serão analisadas na reunião (Entrará na ata os links para facilitar referências).
  - CLI github permite filtros como:
    -  Issues por label por repositório: `gh issue list --label "question" --json title,author` .
    - Issues por projeto: `gh project item-list --format json`. 
    - Poderíamos fazer um filtro para ser rodado no início da reunião para buscar os Issues classificados como `question`. Utilizar a flag `--jq expression` pode ajudar nisso.

**Comment by gabrielbdornas** [comment]
@Andrelamor acredita que a pessoa da dúvida escreva a solução.

**Comment by gabrielbdornas** [comment]
Resolvemos que a categoria a ser criada para os futuros posts será a `Tira dúvidas`.

**Comment by Andrelamor** [comment]
> Resolvemos que a categoria a ser criada para os futuros posts será a `Tira dúvidas`.

https://automatiza-mg.github.io/handbook/blog/category/tira-d%C3%BAvidas/

**Comment by gabrielbdornas** [comment]
> > Resolvemos que a categoria a ser criada para os futuros posts será a `Tira dúvidas`.
> 
> https://automatiza-mg.github.io/handbook/blog/category/tira-d%C3%BAvidas/

Ficou muito bom!

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, inclui em todos os repositórios a label `tira-duvidas`.

![image](https://github.com/automatiza-mg/handbook/assets/49699290/9857755b-0f7b-431b-8f2f-be205c0f448c)

Então, ao criarmos um Issue que será discutido durante nossos encontros das 15 horas (#108) filtraremos estas `labels`.

**Comment by YanVieira1905** [comment]
Minhas sugestão é que incluamos as dúvidas em posts nos sites do automatiza.MG. O dono da dúvida ficaria responsável por escrever a dúvida e a solução, postando no site.

**Comment by gabrielbdornas** [comment]
> Minhas sugestão é que incluamos as dúvidas em posts nos sites do automatiza.MG. O dono da dúvida ficaria responsável por escrever a dúvida e a solução, postando no site.

@YanVieira1905, boa! @Andrelamor também se manifestou desta maneira e eu concordo. Sobre o local, acredito que teremos coisa que fará mais sentido levar p Handbook. Mas acho que esta avaliação poderá ser feita para cada dúvida/resposta.
