### ISSUE TITLE
Acompanhamento projeto Perícia - 20/05/2024

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#112]
- Issues relacionados:
  - https://github.com/automatiza-mg/handbook/issues/88.
  - https://github.com/automatiza-mg/handbook/issues/105
- @YanVieira1905 contou os últimos alinhamentos e encontros com equipe da perícia.
- Importância benchmarking.
- Maria Laura colocou as dúvidas sobre a demanda das agendas.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, conforme conversamos no grupo do Teams, aguardando Maria Laura liberar acesso a transcrição da reunião.

**Comment by Andrelamor** [comment]
@gabrielbdornas acho que seria bom refazermos a sequência dos fluxos (ordenação das partes que cada pessoa está fazendo), pois na listagem inicial https://github.com/automatiza-mg/handbook/issues/87 não ficou claro. A minha parte parece ser totalmente independente da primeira, a não ser que haja uma mudança de campos no BIM.

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas acho que seria bom refazermos a sequência dos fluxos (ordenação das partes que cada pessoa está fazendo), pois na listagem inicial #87 não ficou claro. A minha parte parece ser totalmente independente da primeira, a não ser que haja uma mudança de campos no BIM.

Acho que podemos discutir isso junto com @YanVieira1905.
