### ISSUE TITLE
criar post para robô de conversão de word em pdf

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#131]
Código elaborado em conjunto na primeira seção de Tira-Dúvidas de 17/05/24.

Robô usa Power Shell como alternativa para evitar ações manuais de navegação na interface gráfica do Windows, como `Enviar Teclas` e `Clicar na interface gráfica do usuário` .

Auxílio determinante do @gabrielbdornas que mostrou como perguntarmos para uma ferramenta de IA (no caso, Gemini da Google) uma questão específica, acessível em https://g.co/gemini/share/556e408b9562

**Comment by gabrielbdornas** [comment]
@Andrelamor, só troquei a `label` `webnar` pela `tira-duvidas` para adequar à [governança dos encontros](https://github.com/automatiza-mg/handbook/issues/109#issuecomment-2122678683).
