### ISSUE TITLE
Erro ao clicar em elemento da instância SEI! - Tira Dúvidas - 24/05/2024

### ISSUE THREAD

**Issue by felpsop** [automatiza-mg/handbook#138]
**Descrição:** 

Erro ao clicar em um elemento da instância SEI!, o robô apresenta anomalias inconstantes, sem um previsão exata durante execução do fluxo de impressão dos documentos contidos no processo SEI!.

**Tentativas do usuário:** 

Foram realizados os seguintes testes:

a) Ação "Mover mouse para imagem"
b) Ação "Clicar em elemento da interface do usuário"
c) Ação "Executar função JavaScript"

**Resultados Encontrados:** 

Nenhum dos testes obteve retorno satisfatório.

**Soluções Propostas:**

1. Rezar
2. Chorar

**Resultados Finais:**

**Comment by gabrielbdornas** [comment]
@felpsop, já resolvemos este Issue, correto? Podemos fechá-lo?
