### ISSUE TITLE
Comentar post no handbook

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/handbook#146]
@gabrielbdornas, tentei comentar um post no handbook e no automatiza.mg e não consegui. Você poderia verificar e me orientar por gentileza ? Obrigada.

**Comment by gabrielbdornas** [comment]
@raianecardoso, corrigi o problema:

![image](https://github.com/automatiza-mg/handbook/assets/49699290/8472a5ec-1905-4923-b649-bf70a7fa3279)

Consegue testar p gente se você irá conseguir incluir seu comentário.

**Comment by raianecardoso** [comment]
@gabrielbdornas, comentário incluído [aqui](https://automatiza-mg.github.io/handbook/blog/criando-a%C3%A7%C3%B5es-de-convers%C3%A3o-de-arquivo-com-aux%C3%ADlio-da-ia-e-do-power-shell/#codigo-do-power-shell-com-ajuda-da-ia) com sucesso! Obrigada mais uma vez!

**Comment by Andrelamor** [comment]
@gabrielbdornas @raianecardoso ótimo termos agora a possibilidade de comentar e complementar os posts; como eu não tava taggeado nos comments, só agora li os comentários que vcs fizeram no post de 20/05:
![image](https://github.com/automatiza-mg/handbook/assets/52294411/90fea3be-903b-48b5-9d89-d50a1f21e5b9)

uma sugestão então é sempre enviar o [link do comment](https://github.com/automatiza-mg/handbook/discussions/143#discussioncomment-9998362) pra pessoa que escreveu, uma vez que a marcação não parece ser tão simples quanto num issue, consegui marcar somente @raianecardoso e não @gabrielbdornas

**Comment by gabrielbdornas** [comment]
> uma sugestão então é sempre enviar o [link do comment](https://github.com/automatiza-mg/handbook/discussions/143#discussioncomment-9998362) pra pessoa que escreveu, uma vez que a marcação não parece ser tão simples quanto num issue

@Andrelamor, verdade, o taggeamento não é simples como na construção de um Issue. Meu workaround é buscar o usuário no GitHub e incluir o mesmo com o `@` manualmente no comentário. Não é o mais eficiente, mas tem funcionado. Acho que enviar o link é também uma ótima alternativa.
