### ISSUE TITLE
Fazer post programar BO

### ISSUE THREAD

**Issue by Isabelle-Fernandes** [automatiza-mg/handbook#158]
Fazer post mostrando passo a passo em como programar o BO.

[Acessar ao post](https://automatiza-mg.github.io/handbook/blog/como-programar-o-bo-para-emitir-relat%C3%B3rios/#passo-a-passo)

**Comment by gabrielbdornas** [comment]
@Isabelle-Fernandes, conferi nossa caixa gmail e o [relatório está chegando perfeito](https://mail.google.com/mail/u/0/#inbox/FMfcgzQVxRPHTxknsNtMPxSHcqcltpDs). Agora basta automatizarmos o processo de atualização de nosso [conjunto no PdA](https://dados.mg.gov.br/dataset/servidores-dataset).

**Comment by Isabelle-Fernandes** [comment]
@gabrielbdornas que bom que deu certo! Essa segunda parte me chama que quero aprender junto.
