### ISSUE TITLE
Criar post webnar #8

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/handbook#176]
o @Andrelamor ficou preocupado (😅 ) e resolvi criar esse issue com os seguintes lembretes:
- [x] cortar o final do vídeo antes de subir para o youtube
- [ ] verificar se é possível cortar o vídeo por temas/assuntos tratados.

**Comment by Andrelamor** [comment]
> o @Andrelamor ficou preocupado (😅 ) e resolvi criar esse issue com os seguintes lembretes:
> 
> * [ ]  cortar o final do vídeo antes de subir para o youtube
> * [ ]  verificar se é possível cortar o vídeo por temas/assuntos tratados.

@gabrielbdornas @raianecardoso 
- como nós discutimos, acho que todos concordaram, na última sexta, que avançamos bem no manejo do github e que as dúvidas e casos sobre ele podem ser abordados ao longo da semana no tíra-dúvidas, ou assincronamente mesmo, de forma mais _orgânica_; 
- quanto aos meus comentários ao final do vídeo, de fato eu fico preocupado em tentar aproveitar o nosso tempo para sanar as dúvidas dos alunos do curso de EaD e questões sobre o Power Automate e as demais ferramentas de trabalho que repercutem no público usuário (pois o github é majoritariamente de organização interna)
