### ISSUE TITLE
Incluir no Canva templates para vídeos

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/handbook#192]
@gabrielbdornas, criei, a partir da conta gmail da dcd, uma conta no Canva. Assim, qualquer pessoa da equipe pode utilizar os templates para inclusão de vídeos no YouTube. Gentileza transferir os templates do Automatiza que estão na sua conta pessoal para essa conta da DCD.

**Comment by gabrielbdornas** [comment]
@raianecardoso, feito. Por gentileza, confira se consegue acessar. Atualmente temos 3 thumbnais para os vídeos do YouTube e um projeto com moldes em geral. Vou fechar este isso. Caso ache necessário, fique à vontade para reabri-lo.

**Comment by raianecardoso** [comment]
@gabrielbdornas 

Perfeito, já conferi e está tudo certinho. Valeu demais! :)
