### ISSUE TITLE
Error reading page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/handbook#197]
@gabrielbdornas,  não consegui ligar meu servidor hoje, sendo o erro apresentado : Error reading page 'cursos/python_w3schools/002.md': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> .  Ajuda?

@automatiza-mg/dcd, alguém já passou por isso? 

<img width="1440" alt="Captura de Tela 2024-07-30 às 11 27 17" src="https://github.com/user-attachments/assets/5c48bc92-907d-48bf-8c2f-3babe509b53f">

**Comment by gabrielbdornas** [comment]
@raianecardoso, estranho! Marquei o Issue como `tira-duvidas`. Vamos tentar olhar juntos hoje, 31/07/2024, às 15:00, pode ser?

Você chegou a colocar o erro no Google para ver se acha algum Stackoverflow?

**Comment by raianecardoso** [comment]
@gabrielbdornas 

Consegui resolver com a ajuda desse [post do Stackoverflow](https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica). 

Pela explicação, por eu usar MacOS, eu precisava instalar alguns certificados. Então eu segui a orientação de ir até a pasta Python e rodar o comando Install Certificates.command.

Obrigada!
