### ISSUE TITLE
Propor modelo linha do tempo

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#208]
@YanVieira1905, vou abrir este Isseu conforme acordado em reunião de Faxina de nossos repositórios (#200).

**Comment by gabrielbdornas** [comment]
@YanVieira1905, gostaria de sua opinião [no modelo criado](https://automatiza-mg.github.io/handbook/linha_do_tempo/projeto_fhemig/). Modelo aprovado, acredito que podemos pedir para todas as equipe @automatiza-mg/dcd criarem os arquivos de seus projetos.

**Comment by YanVieira1905** [comment]
@gabrielbdornas, achei excelente. Parece que vai ser fácil de fazer e irá ajudar a registrar essa linha do tempo de forma simplificada. Tenho só algumas questões: A proposta seria construir um por projeto que consta no repositório? Se sim, haveria alguma forma de termos uma visão agregada?

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas, achei excelente. Parece que vai ser fácil de fazer e irá ajudar a registrar essa linha do tempo de forma simplificada. Tenho só algumas questões: A proposta seria construir um por projeto que consta no repositório? Se sim, haveria alguma forma de termos uma visão agregada?

@YanVieira1905, que bom que gostou. Inicialmente pensei em um por projeto sim. Podemos pensar em um gráfico deste para todos os projetos na [página inicial da linha do tempo](https://automatiza-mg.github.io/handbook/linha_do_tempo/).

**Comment by YanVieira1905** [comment]
Podemos fechar sim. Estou de acordo. O modelo é esse mesmo. Será que haveria a possibilidade de fazer essa agregação de forma automática?

**Comment by gabrielbdornas** [comment]
> Podemos fechar sim. Estou de acordo. O modelo é esse mesmo. Será que haveria a possibilidade de fazer essa agregação de forma automática?

Inicialmente acho difícil. Posso pensar.
