### ISSUE TITLE
Introdução ao GitHub - 07/11/2024

### ISSUE THREAD

**Issue by bmdRaphael** [automatiza-mg/handbook#220]
## Objetivo 
O objetivo desta primeira conversa é navegar pelas funcionalidades básicas do GitHub.

#### Quais tópicos já vimos?

- Estrutura geral dos repositórios dentro da organização automatiza-mg
- Padrão de URL das páginas: github/organização/repositório
- Padrão dos menus e submenus
- Issues/'problemas': 
  - como abrir
  - quais informações estão contidas neles
  - como fazer comentários ('planejador' e estilos de formatação serão abordados em próxima conversa)

###### Subtítulos
- Listas com itens
  - Subitens
- Marcações
  - [hiperlinks](https://www.markdownguide.org/basic-syntax/)
  - **negrito**
  - _itálico_   

> Citações (de comentários de colegas)

````
Cópia de códigos
````
- [ ] caixa de marcar conclusão de tarefas
- Nota de rodapé[^1]:

[^1]: para informações complementares, de exemplo, como os detalhes das variáveis de cada subfluxo dos robôs do SEI - vide [exemplo](https://automatiza-mg.github.io/automatizacoes/robos/insere_documento_externo/#montando-o-seu-robo)

**Comment by Andrelamor** [comment]
Que ótimo, @bmdRaphael, muito bom! Vamos aprender juntos como utilizar o github e otimizar nossas rotinas de trabalho, principalmente no uso do Power Automate

**Comment by dudsguedes** [comment]
Estamos realizando um teste para verificar as funcionalidades dos perfis criados.

**Comment by raianecardoso** [comment]
Pessoal, em complementação a introdução que vocês participaram hoje, deixo alguns exemplos de issues em outros repositórios para que vocês vejam os diferentes usos dessa ferramenta: 

- [exemplo de relato de reunião](https://github.com/automatiza-mg/nucleo-imersoes/issues/26)
- [exemplo de tarefas a serem desenvolvidas](https://github.com/automatiza-mg/automatizacoes/issues/162)
- [exemplo de problema encontrado durante o trabalho, no qual foi solicitado a ajuda de um colega](https://github.com/automatiza-mg/aura/issues/16)

**Comment by Andrelamor** [comment]
Pessoal, o que estão achando até aqui? Vamos tentar praticar um pouco? @AndersonLutkenhaus @vitorluizcoelho @Julianafersan 

A partir desta página, poderemos registrar o que estamos aprendendo e irmos recheando juntos o escopo deste [comentário inicial](https://github.com/automatiza-mg/handbook/issues/220#issue-2640911177)

**Comment by AndersonLutkenhaus** [comment]
Apesar de ser tudo novo para mim, entendo como uma ferramenta importante de registro, possibilidade de diálogo e posicionamento, conforme a disponibilidade de cada servidor. Excelente!

**Comment by Iannarelli-iann** [comment]
Boa tarde, André!

Estou gostando, mas com uma certa dificuldade de entender o inglês, nunca fui boa na matéria, mas aos poucos, como disse, vamos adaptando com a linguagem dele. E desafios são sempre bons, né!

#boraaprender#

**Comment by Andrelamor** [comment]
## Pauta dia 21/11

1. simulação das alterações de 2 robôs do SEI a partir das sugestões do @vitorluizcoelho: https://github.com/automatiza-mg/handbook/issues/223
2. formulação do problema/tarefa comentado pela @Iannarelli-iann da captura de textos em pdf

**Comment by Andrelamor** [comment]
## Sugestões de pauta dia 28/11

1. demonstração do planner por @Andrelamor 
2. simulação das alterações de um robô do SEI pelo @vitorluizcoelho a partir das sugestões do @kinzinho666 em https://github.com/automatiza-mg/biblioteca-de-robos/pull/24
3. fechamento do https://github.com/automatiza-mg/handbook/issues/226 pela @Iannarelli-iann

**Comment by Andrelamor** [comment]
> #### Markdown
> ###### Subtítulos
> * Listas com itens
>   
>   * Subitens
> * Marcações
>   
>   * [hiperlinks](https://www.markdownguide.org/basic-syntax/)
>   * **negrito**
>   * _itálico_
> 
> > Citações (de comentários de colegas)
> 
> ```
> Cópia de códigos
> ```
> 
> * [ ]  caixa de marcar conclusão de tarefas
> * Nota de rodapé[1](#user-content-fn-1-dc815a0c8a75b3eed425d3bfc9e9887a):
> 
> ## Footnotes
> 1. para informações complementares, de exemplo, como os detalhes das variáveis de cada subfluxo dos robôs do SEI - vide [exemplo](https://automatiza-mg.github.io/automatizacoes/robos/insere_documento_externo/#montando-o-seu-robo) [↩](#user-content-fnref-1-dc815a0c8a75b3eed425d3bfc9e9887a)

## Outras feramentas úteis em markdown

- [link markdown preview](https://markdownlivepreview.com/)
- [conversor de markdown em tabelas e outros formatos](https://tableconvert.com/markdown-to-excel)
