### ISSUE TITLE
ideia para post sobre retirada de escaping em textos copiados- Tira Dúvidas 12/11/2024

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#222]
@dudsguedes numa próxima sessão sobre o github, podemos escrever sobre teu caso hoje que pode ajudar em outras situações: como retirar nova linha de um texto capturado como variável que contenha uma linha indesejável, passível de ser retirado em ação do PA. Exemplo genérico:
- variável capturada
````
<Texto linha desejada> \r
<Linha vazia indesejável>
````
- variável desejada
````
<Texto linha desejada>
````

**Comment by dudsguedes** [comment]
![image](https://github.com/user-attachments/assets/0ce12755-d566-4245-8b9f-02757c2dfdda)

**Comment by dudsguedes** [comment]
![WhatsApp Image 2024-11-19 at 15 08 10](https://github.com/user-attachments/assets/42a323d2-d423-4a50-8e1b-d74b8f24b0a8)
