### ISSUE TITLE
problemas na leitura e cópia de textos baixados da web em pdf

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#226]
## Problema

Ações que não estão funcionando como esperado:
- copiar texto de PDF via área de transferência (Crtl A, Crtl+C e Obter texto da área de transferência), no arquivo aberto no navegador Chrome em nova aba (histórico de downloads)
- se a página da Web contiver texto, no arquivo aberto no navegador Chrome em nova aba (histórico de downloads)

#### a estrutura das condicionais no código: ![image](https://github.com/user-attachments/assets/1441494d-1ec8-4929-a833-ba4676d5ab9b)
- o resultado adverso (não reconheceu o texto do primeiro `If` 'COM EFEITO DE NEGATIVA') 
![image](https://github.com/user-attachments/assets/109d8454-d277-4b27-9eb2-89d218d9d2a6)
#### para a mesma certidão da mesma empresa acima, usando outra estratégia de leitura do texto, via área de transferência, mesmo problema: 
![image](https://github.com/user-attachments/assets/4d4181ce-530d-433c-b9a5-4c355eb88c32)
#### a variável nem foi lida corretamente, por isso a classificação como 'Não contém NEGATIVA' foi aplicada: 
![image](https://github.com/user-attachments/assets/1a2a7007-8117-42ac-a7be-fd05b38673b5)

## Solução

- Utilizar função de `Extrair texto do PDF`, após `Aguardar o arquivo` e `Cortar texto` com os parâmetros desejados, para obter os valores de texto necessários.

![image](https://github.com/user-attachments/assets/e14ab519-9b77-46af-996e-c3539f39ed6e)

![image](https://github.com/user-attachments/assets/5721cfaf-05e7-4728-a315-670fbf44c097)

**Comment by Andrelamor** [comment]
Agradecimentos à @Isabelle-Fernandes pela
> ## Solução

@Iannarelli-iann veja por favor se a Solução acima não é o mesmo caso para resolver teu erro!

**Comment by Iannarelli-iann** [comment]
Bom dia!

      Agradeço também a @Isabelle-Fernandes e a você, @Andrelamor pela Solução de o desafio que estava sendo o copiar um texto (no meu caso um número de processo/autos) e colar na planilha.
E ficou assim:

##Solução##

![image](https://github.com/user-attachments/assets/72d4c087-9d15-461e-aff9-61231a8d2132)
