### ISSUE TITLE
Testar código power shell para anexar arquivos da área de transferência com Ctrl+V

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#230]
## Objetivo
Facilitar a operação de robôs que necessitem anexar arquivos em emails para enviá-los, sem precisar de navegar na interface do windows (procurando nas pastas com tabs e etc).
Este pedaço de robô vai copiar um arquivo em excel para a área de transferência e anexá-lo no Outlook Mail, **já logado manual e previamente, sem enviar o email a nenhum destinatário**. 

## Passos para testar 

1. Entrar no outlook email
2. Copiar e colar o código no power automate
- Que está [ali embaixo](https://github.com/automatiza-mg/handbook/issues/230#issuecomment-2515574122)
3. Fixar variáveis de entrada para o script do powershell (que é chamado na ação 5)
 
![image](https://github.com/user-attachments/assets/3b49885e-9f48-4828-9963-76e5b1300335)

  - 3.1. escolher um arquivo qualquer em excel e salvar o caminho da sua pasta em `caminho_planilha`;
  - 3.2. copiar parte do nome do arquivo e salvar em `parte_nome`

**Mas pra quê isso?** Porque essa estrutura pode ser muito útil em _loops_ que vão salvar arquivos dinamicamente com um padrão que precise ser captado no script do Power Shell 

Num loop que varie conforme o ano, salvando uma planilha excel para cada ano, teríamos p. ex.: `unidade_2013`, `unidade_2014`, `unidade_200X` e por aí vai...o padrão da variável dinâmica seria a variável `%ano%`.

No meu caso, usei uma variável genérica `%parte_nome%`.

**Comment by Andrelamor** [comment]
````
WebAutomation.LaunchChrome.LaunchChrome Url: $'''https://outlook.office.com/mail/''' WindowState: WebAutomation.BrowserWindowState.Maximized ClearCache: False ClearCookies: False WaitForPageToLoadTimeout: 60 Timeout: 60 PiPUserDataFolderMode: WebAutomation.PiPUserDataFolderModeEnum.AutomaticProfile TargetDesktop: $'''{\"DisplayName\":\"Computador local\",\"Route\":{\"ServerType\":\"Local\",\"ServerAddress\":\"\"}}''' BrowserInstance=> Browser
WAIT 6
MouseAndKeyboard.SendKeys.FocusAndSendKeys TextToSend: $'''N''' DelayBetweenKeystrokes: 40 SendTextAsHardwareKeys: False
Clipboard.Clear _
@@copilotGeneratedAction: 'False'
Scripting.RunPowershellScript.RunPowershellScript Script: $'''Add-Type -AssemblyName System.Windows.Forms

# Define o diretório onde os arquivos estão localizados
$directoryPath = \"%caminho_planilha%\"

# Define o padrão do nome dos arquivos (sem os números)
$fileNamePattern = \"%parte_nome%\"

# Busca os arquivos que contêm o padrão do nome
$filePaths = Get-ChildItem -Path $directoryPath -Filter \"$fileNamePattern*.xls\" | Select-Object -ExpandProperty FullName

# Cria uma StringCollection para armazenar os caminhos dos arquivos
$files = New-Object System.Collections.Specialized.StringCollection

# Adiciona cada caminho de arquivo à coleção
foreach ($filePath in $filePaths) {
    $files.Add($filePath)
}

# Define os arquivos na área de transferência
[System.Windows.Forms.Clipboard]::SetFileDropList($files)''' ScriptOutput=> PowershellOutput
WAIT 4
MouseAndKeyboard.SendKeys.FocusAndSendKeys TextToSend: $'''{Tab}{Tab}{Tab}{Control}({V})''' DelayBetweenKeystrokes: 40 SendTextAsHardwareKeys: True

````

**Comment by Iannarelli-iann** [comment]
Bom dia, @Andrelamor!

Copiei o código como informado, mas o robô apenas abriu o _Outlook_ e não anexou nada.
Por gentileza, pode verificar o que fiz de errado?

![image](https://github.com/user-attachments/assets/fa7800ac-bb13-4af3-be65-903cc256673f)

![image](https://github.com/user-attachments/assets/56707549-1d9e-4540-835f-ad7301344417)

Grata!
