### ISSUE TITLE
Alinhamento semanal - 15/01/2024 a 19/01/2024

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#57]
- Análise de todos os Issues listados no [Backlog](https://github.com/orgs/automatiza-mg/projects/1/views/2).
- Definições gerais:
  -  Atuação na lista dos agentes de simplificação.
  - Limpeza dos Issues em backlog que não faziam mais sentido.

**Comment by Andrelamor** [comment]
Também modificamos as views do planner, de forma a evidenciar as tarefas em _ToDo_ e _Work IN Progress_
