### ISSUE TITLE
reunião SEDE 31-01-24

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#63]
SEDE (DSAN): Banes, Gianluca, Josiane

## contexto
- acúmulo processos no SIAPLE aguardando conclusão nesse sistema (podem já ter NT elaborado pela área técnica, vide gráfico de pizza abaixo)

## propósitos da parceria/projeto e possíveis ações
- automatizar processo de criar e despachar documentos no SEI para pareceres no SIAPLE
- reutilização de robôs já existentes
- robô de parecer técnico (90% das ações do protótipo disponibilizado pela Isa)
- secretário disposto a utilizar IA para automatizar elaboração dos pareceres com impacto econômico ( @Andrelamor com base em qual sistema de regras?)

## fluxo
![image](https://github.com/automatiza-mg/handbook/assets/52294411/6de8ccfa-1d1e-4cd9-bd41-193128e3f6a3)

- email da SEGOV notificando a SEDE, com o PL tramitado no SIAPLE
- SEDE acompanha resposta de outros órgãos (?) segundo Banes; SEDE só se manifesta de acordo com a temática desenvolvimento econômico (Josiane); parecer 'dividido' não é coordenado pela SEDE
- SEGOV acompanha respostas de outros órgãos, segundo Josiane
- IF competência 'não-afeta': SEDE tramita diretamente no SIAPLE para secretária adjunta remeter de volta à SEGOV, com frase sucinta ('...não é de competência...')
    - ELSE 'afeta' (avaliação SEDE): processo SEI 
    - ELSE possibilidade de pedido de RE-ANÁLISE da SEGOV para a SEDE, tempos após, mesmo sendo classificada como 'não-afeta'
- acesso SIAPLE restrito ao gabinete e à DSAN
- planilha de controle interno com medida de priorização definida pelo Banes (ex.: vetos com urgência, aprovações com urgência)
- arquivo do PL disponível mo SIAPLE e na ALMG
- questão dos prazos depende muito da priorização da própria SEGOV e do governo com a ALMG
- situação das NT (jan/23 a jan/24)

![image](https://github.com/automatiza-mg/handbook/assets/52294411/a81d0360-55e0-4f47-9a58-91f6275eff33)
- grande maioria dos pedidos de reanálise é das NTs marcados como 'não-afetas' (12 em um ano - ?)
- informações complementares ao SIAPLE precisam ser consultadas no site da ALMG (infos do autor, da tramitação - eg. em qual comissão se encontra no momento da análise)
- áreas fazer parecer como um todo ou parte específica do projeto? DISAN faz o trabalho de discriminar a qual conteúdo compete cada área
- Secretário determinou que sempre todo PL seja encaminhado à área técnica da SEDE, mesmo que aparentemente 'não-complexo'
- arquivo final de NT ao PL (modelo AGE) é o que será anexado ao SIAPLE

## ideias de implementação
- a partir da NT elaborada: criar processo SEI, copiar conteúdo e anexar no SIAPLE
- Yan: a partir do PL (classificar de acordo com competências); conferência humana ao final do parecer concluído; integração com chat GPT ou consulta direta para conteúdo do processo como um todo
    - Gabriel: possibilidade de treinar a ferramenta com base de conhecimento
    - André: sugestão de adotar classificação inicial para evitar viesamento das bases (que devem ser limitadas) - Banes concordou
    - Banes sugeriu 3 filtros de revisão (ler; termo simples; comunicação + objetiva)

**Comment by gabrielbdornas** [comment]
@Andrelamor, por se tratar de ata de reunião já ocorrida, vou fechar o Issue. Tudo bem?
