### ISSUE TITLE
reunião projeto HUB CGE Setorial SEPLAG 02-02-24

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#64]
projeto HUB 

- Ana Carolina de Aguiar Vicente
    - expertise sistemas está na CGE, área da Cynthia
    - proposta geral
    - relatório de contratações de maior risco para acesso da SUBCOMP, com levantamento de fornecedores e apuração de risco de integridade
    - política de relcionamento com fornecedores derivada da consulta elaborada dessa proposta de projeto
    - compilar bases de dados importantes para verificação do fornecedor; ora pela CGE, ora pelo jurídico, ora pela SUBCOMP
    - **pouca ferramenta para determinar ações se risco alto de contratação**
    
- Yan
    - proposta com integração requerida de 31 sistemas 
    - qual tipo de integração desejada?
    - cálculo do custo X benefício? 
    - **integração mais propícia no datalake**
        - área do Diniz
    - automatização na consulta/RPA (simulação da atividade humana)
        - exemplo: consulta ao CAFIMP
- 2 rodada Yan:
    - escopo limitado da diretoria
    - papel TI SEPLAG para integração via _datalake_
- Cynthia
    - levantamento UAI Risks das contratações; resolução de riscos de contratação em elaboração com a SUBCOMP
    - proposta da CGE setorial complementa resolução, inspirada em iniciativas da iniciativa privada (receita, processos judiciais, situação tributária), para elaborar um report
    - ferramenta deveria gerar alerta **durante o pregão** para desa (PNPC governo federal já incorpora regras de negíocio de riscos de contratações - avaliaçõss de perfil dos fornecedores)
    - **datalake pode ajudar a organizar fontes de consulta**
    - **parte residual em consultar sites federais - parte RPA**
    - exemplo de lista de trabalho escravo produzida pelo Tribunal do Trabalho - insumos para rankear fornecedores numa escala de riscos
    - **pouco arcabouço para impedir contratações baseado em avaliação de riscos**
    - nem sempre tem ferramenta para impugnar concorrente, mas às vezes tem (vínculo familiar oculto em empresas de fachada para 'concorrer' - exemplo Jafer) - fornecedor começa a ter mais trabalho para burlar o sistema
    - _datalake_ dependente de fonte de financiamento do recursos; necessidade provocada e reiterada pelo TCE
    - qual formato da entrega? report? excel? a ideia é criar banco de dados, hoje recebem para montar bases

- André
- conversa conosco já é desdobramento de uma conversa preliminar com a SUBCOMPRAS?
    - teve um indicativo de adesão da subsecretária
- existe resolução de riscos da SUBCOMPRAS?
    - assuntos sendo discutidos no comitê, com indicativos a partir dos processos mapeados 
    - apetite a riscos ao final do processo, declarado 
    - resolução de risco das contratações da CGE

- Danielle
    - planilha situação fornecedores 

## encaminhamentos propostos pelo @YanVieira1905 

- peneirar a lista preliminar (quais seriam as _blacklists_ mais severas indicadas pelo mapeamento dos riscos?)
    - o que se tem acesso hoje?
    - captar algo além do que não se tem acesso
- precisamos enteder o que é possível consultar
    - refinar escopo da demanda, entender o que é possível consultar via RPA; formato de entrega é posterior à avaliação dessas possibilidades

**Comment by gabrielbdornas** [comment]
@Andrelamor e @YanVieira1905, fechando este issue, pois acredito que se trata de uma ata de reunião já ocorrida.
