### ISSUE TITLE
Novo projeto validação atestados médicos (FHEMIG) - Acesso API

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#66]
Este novo projeto exigirá o consumo da API CRM para busca de informações básicas do médico responsável pelo atestado.

Para conseguir este acesso deveremos solicitar a liberação para o CFM, conforme orientado [neste link](https://sistemas.cfm.org.br/listamedicos/informacoes). Em contato com Aline no número (61) 3445-5955, fui informado que inclusive órgãos públicos devem criar um acesso de usuário externo no SEI-Medicina. Após este cadastro o pedido no nome do dirigente máximo do órgão que está solicitando poderá ser realizado. **Ainda segundo Aline, o prazo, em média, para recebimento das chaves de acesso são de um mês**.

Tendo em vista que o projeto será realizado entre SEPLAG e FHEMIG, acredito que o melhor seria solicitar este acesso via Presidência da FHEMIG.

## Ações

- [x] Criação usuário externo FHEMIG SEI-Medicina.
- [x] Enviar documentação necessária dirigente máximo FHEMIG para liberação de acesso.
- [x] Envio solicitação acesso API.
- [x] Recebimento chaves de acesso.
- [ ] Testes finais.

**Comment by gabrielbdornas** [comment]
Protocolo de pedido de acesso a api [recebido em e-mail pessoal](https://mail.google.com/mail/u/0/#inbox/FMfcgzGxSHlMPRlrFzPtjstwKtQWSXvZ).

**Comment by YanVieira1905** [comment]
Para conferência de nome de servidor e MASP estava pensando inicialmente em utilizarmos o relatório do BO. No entanto, ao olhar o portal da transparência, acho que podemos conseguir estes dados por lá. @gabrielbdornas e @Andrelamor sabem se existe algum banco de dados ou api que possamos consultar o nome e masp do servidor?

**Comment by Andrelamor** [comment]
> Para conferência de nome de servidor e MASP estava pensando inicialmente em utilizarmos o relatório do BO. No entanto, ao olhar o portal da transparência, acho que podemos conseguir estes dados por lá. @gabrielbdornas e @Andrelamor sabem se existe algum banco de dados ou api que possamos consultar o nome e masp do servidor?

@YanVieira1905 a relação nominal de servidores é publicada desde ano passado no Portal de Transparência, [neste link](https://www.transparencia.mg.gov.br/estado-pessoal); o robô pode acessar `relação nominal de servidores`, e ser direcionado para [este drive](https://drive.google.com/drive/u/0/folders/17AmYO39aZTX_S34dI6tYUbSJDB-jy5Wh), no qual poderia ser acessado arquivo mensal mais recente, ou referente ao mês do atestado.
O nome do arquivo tem um padrão `AAAAMM` que indica ano e mês de referência, que seria mais adequado que a 'última modificação' (perceba que teve alguma revisão no arquivo de julho de 2020 e ele foi para o top 3 da lista)

**Comment by gabrielbdornas** [comment]
> @YanVieira1905 a relação nominal de servidores é publicada desde ano passado no Portal de Transparência, [neste link](https://www.transparencia.mg.gov.br/estado-pessoal); o robô pode acessar `relação nominal de servidores`, e ser direcionado para [este drive](https://drive.google.com/drive/u/0/folders/17AmYO39aZTX_S34dI6tYUbSJDB-jy5Wh), no qual poderia ser acessado arquivo mensal mais recente, ou referente ao mês do atestado.
> O nome do arquivo tem um padrão `AAAAMM` que indica ano e mês de referência, que seria mais adequado que a 'última modificação' (perceba que teve alguma revisão no arquivo de julho de 2020 e ele foi para o top 3 da lista)

@YanVieira1905 e @Andrelamor, agora que poderemos criar máquinas virtuais podemos criar uma API para fazer este trabalho. Acho que ficará mais rápido. O ETL poderia atualizaria as informações periodicamente e o Automate somente chamaria o endpoint, ao invés de carregar todos os arquivos por consulta.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, recebemos em 20/03/2024 acesso à API.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, vou fechar o Issue por entender que a lista em `.csv` vai te auxiliar. Se precisar de auxílio para usar o web service, pode me chamar.
