### ISSUE TITLE
reunião DCD 2024-04-01

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/handbook#83]
- 4 servidores da SEJUSP, 1 ficará em apenas um mês
- projetos
  - iniciar perícia médica (SEPLAG), autos de infração e SEJUSP em paralelo
  - iniciar análise de autos de infração (CET); 
    - leilões e jurídico em suspenso (vide https://github.com/automatiza-mg/handbook/issues/81)
  - SEJUSP: RH + financeiro (reunião geral a ser marcada para lab.mg, preenchimento formulário)
  - SCAP: @Andrelamor seguir com formulação do arquivo para Carla; fechar relatório B.O. (de-para); robô para configurar para buscar outros campos no SIAD; B.O. enviar relatório para e-mail periodicamente com campos localizados no de-para
- lançamento Automatiza 09/04
  - readequação caminhos URL domínio SEPLAG: caso não seja possível, deixar ocmo está
  - analytics: pega todas as páginas do domínio e ainda não foi plugado (previsão até sexta)
  - site: readequações na _landing page_ feitas durante a reunião;
  - curadoria dos MVPs com @gabrielbdornas 
  - curso: subir aulas já vistas, até 8 @augustacora

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, já publiquei todas as modificações que fizemos no automatiza ao longo de nossa reunião, commits relacionados acima.
