### ISSUE TITLE
Reunião perícia médica 18/04/2024

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#87]
Pontos interessantes/necessários:

- Necessidade de validação do CPF informado durante o preenchimento do formulário de solicitação.
- Discutir a necessidade de anexar identidade. Área logada resolveria a questão.
- Buscar informações BIM no SISAP.
- Discutir necessidade de assinatura física ao final do processo. Assinatura SEI vale como assinatura.
- Discutir início com processos novos para servidores que tem apenas uma solicitação. Não deixar o passivo aumentar. Ter que juntar processos pode ser um problema para o robô.
- Documental só é negada se algo ferir a legislação. Não dá para negar paciente não atendido.
- Atestado é OBRIGATÓRIO ter CID. Caso não tenha CID não haverá licença.
- Não existe atestado pré-datado.
- Assinatura do termo de confidencialidade para as próximas reuniões.
- RPM poderia ser visualizado via BO?

**Comment by Andrelamor** [comment]
@gabrielbdornas aparentemente o BO traria sim, mas consultei 2 casos que não retornaram infos de pericia médica, somente outros tipos de afastamento
> * RPM poderia ser visualizado via BO?
![image](https://github.com/automatiza-mg/handbook/assets/52294411/c71c8564-186a-4fcf-90ca-db815bb0062f)

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas aparentemente o BO traria sim, mas consultei 2 casos que não retornaram infos de pericia médica, somente outros tipos de afastamento

Estranho. Será que conseguimos conversar com alguém da PRODEMGE para entender por quê?
